services:
  mongodb:
    image: mongodb/mongodb-enterprise-server
    container_name: csfle-demo-mongo
    restart: unless-stopped
    ports:
      - "47017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: csfle_demo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
